name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Obter o código do projeto
        uses: actions/checkout@v4

      - name: Autenticação no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construção da imagem Docker
        run: echo "Executando o comando Docker Build"

      - name: Envio da imagem Docker
        run: echo "Executando o comando Docker Push"

  cd:
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - name: Autenticação na AWS
        run: echo "Executando o comando aws configure"

      - name: Configurar o kubectl
        run: echo "Executando o comando aws update-kubeconfig"

      - name: Deploy dos manifestos no Kubernetes
        run: echo "Executando o comando kubectl apply"

         
    
